import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest


def _load_script_module(script_name: str):
    script_path = Path(__file__).resolve().parents[2] / "scripts" / script_name
    spec = importlib.util.spec_from_file_location(f"{script_name}_module", script_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


setup_remote_reranker_provider = _load_script_module("setup_remote_reranker_provider.py")


def test_remote_reranker_setup_plan_matches_dgx_defaults() -> None:
    plan = setup_remote_reranker_provider.build_setup_plan(route_host="192.168.20.243")

    assert plan.service_name == "nex-pcx-reranker-provider"
    assert plan.systemd_unit_name == "nex-pcx-reranker-provider.service"
    assert plan.workdir == "/home/nexpcx/2607_nex_pcx"
    assert plan.python_bin == "/home/nexpcx/2607_nex_pcx/.venv/bin/python"
    assert plan.models_dir == "/home/nexpcx/2607_nex_pcx/models"
    assert plan.model_dir_name == "qwen3_reranker_4b"
    assert plan.route_base_url == "http://192.168.20.243:9104"
    assert plan.health_url == "http://192.168.20.243:9104/healthz"
    assert plan.launch_plan.backend == "qwen_reranker"
    assert plan.launch_plan.host == "0.0.0.0"
    assert plan.launch_plan.port == 9104
    assert plan.request_smoke_command == (
        "./.venv/bin/python",
        "scripts/run_remote_reranker_request_smoke.py",
        "--base-url",
        "http://192.168.20.243:9104",
        "--markdown-output",
        "artifacts/remote_reranker_request_smoke.md",
    )
    assert plan.operations_status_command == (
        "./.venv/bin/python",
        "scripts/run_remote_reranker_background.py",
        "smoke",
        "--route-host",
        "192.168.20.243",
        "--port",
        "9104",
        "--markdown-output",
        "artifacts/remote_reranker_systemd_smoke.md",
    )


def test_remote_reranker_setup_renders_env_without_app_database_secret() -> None:
    plan = setup_remote_reranker_provider.build_setup_plan(
        route_host="192.168.20.243",
        provider_model_id="Qwen/Qwen3-Reranker-4B",
    )

    env_text = setup_remote_reranker_provider.render_env_file(plan)

    assert env_text.startswith("# Generated by scripts/setup_remote_reranker_provider.py")
    assert "NEX_PCX_RERANKER_PROVIDER_BACKEND=qwen_reranker" in env_text
    assert "NEX_PCX_RERANKER_PROVIDER_DEVICE=cuda:0" in env_text
    assert "NEX_PCX_RERANKER_PROVIDER_MODEL_DIR_NAME=qwen3_reranker_4b" in env_text
    assert "NEX_PCX_DATABASE_URL" not in env_text
    assert "nuri1004" not in env_text


def test_remote_reranker_setup_renders_systemd_unit() -> None:
    plan = setup_remote_reranker_provider.build_setup_plan(route_host="192.168.20.243")

    unit_text = setup_remote_reranker_provider.render_systemd_unit(plan)

    assert "Description=NeX-PCX reranker provider (qwen-reranker-primary)" in unit_text
    assert "User=nexpcx" in unit_text
    assert "Group=nexpcx" in unit_text
    assert "WorkingDirectory=/home/nexpcx/2607_nex_pcx" in unit_text
    assert (
        "EnvironmentFile=/home/nexpcx/2607_nex_pcx/deployment/env/" "nex-pcx-reranker-provider.env"
    ) in unit_text
    assert (
        "ExecStart=/home/nexpcx/2607_nex_pcx/.venv/bin/python -m uvicorn "
        "app.reranker_provider_service:app --host 0.0.0.0 --port 9104"
    ) in unit_text
    assert "NoNewPrivileges=true" in unit_text
    assert "WantedBy=multi-user.target" in unit_text


def test_remote_reranker_setup_renders_user_systemd_unit_and_readme() -> None:
    plan = setup_remote_reranker_provider.build_setup_plan(
        route_host="192.168.20.243",
        systemd_dir="/home/nexpcx/.config/systemd/user",
    )

    unit_text = setup_remote_reranker_provider.render_systemd_unit(plan, user_systemd=True)
    readme_text = setup_remote_reranker_provider.render_operator_readme(
        plan,
        user_systemd=True,
    )

    assert "User=nexpcx" not in unit_text
    assert "Group=nexpcx" not in unit_text
    assert "network-online.target" not in unit_text
    assert "NoNewPrivileges=true" not in unit_text
    assert "PrivateTmp=true" not in unit_text
    assert "WantedBy=default.target" in unit_text
    assert "systemctl --user enable --now nex-pcx-reranker-provider.service" in readme_text
    assert "loginctl show-user nexpcx -p Linger" in readme_text


def test_remote_reranker_setup_writes_files(tmp_path: Path) -> None:
    plan = setup_remote_reranker_provider.build_setup_plan(
        workdir=str(tmp_path / "2607_nex_pcx"),
        env_dir=str(tmp_path / "env"),
        systemd_dir=str(tmp_path / "systemd-user"),
        route_host="192.168.20.243",
    )

    env_file, unit_file, readme_file = setup_remote_reranker_provider.write_plan_files(
        plan,
        user_systemd=True,
    )

    assert env_file.exists()
    assert unit_file.exists()
    assert readme_file.exists()
    assert "NEX_PCX_RERANKER_PROVIDER_BACKEND=qwen_reranker" in env_file.read_text(encoding="utf-8")
    assert "User=" not in unit_file.read_text(encoding="utf-8")
    assert "curl -fsS http://192.168.20.243:9104/healthz" in readme_file.read_text(encoding="utf-8")


def test_remote_reranker_setup_accepts_service_name_with_service_suffix() -> None:
    plan = setup_remote_reranker_provider.build_setup_plan(
        service_name="nex-pcx-reranker-provider.service",
        route_base_url="https://reranker.example",
    )

    assert plan.service_name == "nex-pcx-reranker-provider"
    assert plan.systemd_unit_name == "nex-pcx-reranker-provider.service"
    assert plan.operations_status_command[-4:] == (
        "--port",
        "443",
        "--markdown-output",
        "artifacts/remote_reranker_systemd_smoke.md",
    )


@pytest.mark.parametrize(
    ("kwargs", "message"),
    [
        ({"service_name": "bad/service"}, "service_name may only contain"),
        ({"service_name": ".service"}, "service_name is required"),
        ({"route_base_url": "192.168.20.243:9104"}, "route_base_url must be"),
        ({"model_dir_name": " "}, "model_dir_name is required"),
        ({"user": " "}, "user is required"),
    ],
)
def test_remote_reranker_setup_rejects_invalid_values(kwargs: dict[str, str], message: str) -> None:
    with pytest.raises(ValueError, match=message):
        setup_remote_reranker_provider.build_setup_plan(**kwargs)


def test_remote_reranker_setup_cli_prints_json_plan() -> None:
    result = subprocess.run(
        [
            sys.executable,
            "scripts/setup_remote_reranker_provider.py",
            "--route-host",
            "192.168.20.243",
            "--user-systemd",
            "--json",
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    payload = json.loads(result.stdout)
    plan = payload["plan"]

    assert payload["wrote_files"] is False
    assert payload["user_systemd"] is True
    assert plan["systemd_unit_name"] == "nex-pcx-reranker-provider.service"
    assert plan["route_base_url"] == "http://192.168.20.243:9104"
    assert "app.reranker_provider_service:app" in plan["launch_shell_command"]


def test_remote_reranker_setup_cli_writes_user_systemd_files(tmp_path: Path) -> None:
    env_dir = tmp_path / "env"
    systemd_dir = tmp_path / "systemd-user"
    result = subprocess.run(
        [
            sys.executable,
            "scripts/setup_remote_reranker_provider.py",
            "--route-host",
            "192.168.20.243",
            "--env-dir",
            str(env_dir),
            "--systemd-dir",
            str(systemd_dir),
            "--user-systemd",
            "--write-files",
            "--json",
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    payload = json.loads(result.stdout)
    unit_file = systemd_dir / "nex-pcx-reranker-provider.service"
    readme_file = systemd_dir / "nex-pcx-reranker-provider.README.md"

    assert payload["wrote_files"] is True
    assert unit_file.exists()
    assert readme_file.exists()
    assert "User=" not in unit_file.read_text(encoding="utf-8")
